# Generated by Django 6.0.1 on 2026-03-05 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniprofile',
            name='resume',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('CSE', 'Computer Science & Engineering'), ('CSM', 'CSE with Artificial Intelligence & Machine Learning'), ('AID', 'Artificial Intelligence & Data Science'), ('AIML', 'Artificial Intelligence & Machine Learning'), ('CSO', 'CSE with Internet of Things'), ('CIC', 'CSE with IoT and Cyber Security including Blockchain Technology'), ('ECE', 'Electronics & Communication Engineering'), ('EEE', 'Electrical & Electronics Engineering'), ('IT', 'Information Technology'), ('CIV', 'Civil Engineering'), ('MEC', 'Mechanical Engineering')], max_length=10, null=True),
        ),
    ]
